<?php
// module/Album/view/album/album/index.phtml:
$title = 'Partners';
print($this->headTitle($title));
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('album', array('action'=>'add'));?>">Add new Partner</a>
</p>

<table class="table">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>&nbsp;</th>
    </tr>

    <?php foreach ($albums as $album) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($album->id);?></td>
            <td><?php echo $this->escapeHtml($album->artist);?></td>
            <td>
                <a href="<?php echo $this->url('album',
                    array('action'=>'edit', 'id' => $album->id));?>">Edit</a>
                <a href="<?php echo $this->url('album',
                    array('action'=>'delete', 'id' => $album->id));?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>